export const PostContent = [
  {
    imageUrl: "/assets/images/temp/post.png",
    categories: ["featured", "news"],
    estate: 'beveridge',
    title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    buttonLink: "#",
    date: "2021-09-12T03:31:20+0000",
  },
  {
    imageUrl: "/assets/images/temp/post.png",
    categories: ["featured", "news"],
    estate: 'beveridge',
    title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    buttonLink: "#",
    date: "2021-09-12T03:31:20+0000",
  },
  {
    imageUrl: "/assets/images/temp/post.png",
    categories: ["featured", "news"],
    estate: 'beveridge',
    title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    buttonLink: "#",
    date: "2021-09-12T03:31:20+0000",
  },
  {
    imageUrl: "/assets/images/temp/post.png",
    categories: ["featured", "news"],
    estate: 'beveridge',
    title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    buttonLink: "#",
    date: "2021-09-12T03:31:20+0000",
  },
  {
    imageUrl: "/assets/images/temp/post.png",
    categories: ["featured", "news"],
    estate: 'beveridge',
    title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    buttonLink: "#",
    date: "2021-09-12T03:31:20+0000",
  },
  {
    imageUrl: "/assets/images/temp/post.png",
    categories: ["featured", "news"],
    estate: 'beveridge',
    title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    buttonLink: "#",
    date: "2021-09-12T03:31:20+0000",
  },
  {
    imageUrl: "/assets/images/temp/post.png",
    categories: ["featured", "news"],
    estate: 'beveridge',
    title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    buttonLink: "#",
    date: "2021-09-12T03:31:20+0000",
  },
  {
    imageUrl: "/assets/images/temp/post.png",
    categories: ["featured", "news"],
    estate: 'beveridge',
    title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    buttonLink: "#",
    date: "2021-09-12T03:31:20+0000",
  },
  {
    imageUrl: "/assets/images/temp/post.png",
    categories: ["featured", "news"],
    estate: 'beveridge',
    title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    buttonLink: "#",
    date: "2021-09-12T03:31:20+0000",
  },
  {
    imageUrl: "/assets/images/temp/post.png",
    categories: ["featured", "news"],
    estate: 'beveridge',
    title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    buttonLink: "#",
    date: "2021-09-12T03:31:20+0000",
  },
];
